FROM node:18.19.1

RUN apt-get update && apt-get install gnupg wget git -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --de>
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sou>
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*
RUN apt-get update  && apt-get install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 lib>

WORKDIR /app/botzdg

RUN git clone https://github.com/gusquadri/botzdgfixed

WORKDIR /app/botzdg/botzdgfixed

RUN npm install

CMD ["npm", "start"]